language: php

php:
  - 5.2
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh createTempDirectory.sh
  - chmod -R 777 ./app/tmp
  - cp app/Config/core.php.default app/Config/core.php
  - cp app/Config/config.php.default app/Config/config.php
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'host' => '127.0.0.1',
      'login' => 'root',
      'persistent' => false,
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'host' => '127.0.0.1',
      'login' => 'root',
      'persistent' => false,
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    }" > app/Config/database.php
  - sh app/Console/cake autoschema create GeoCoordinates
  - sh app/Console/cake autoschema create WikiPages
  - sh app/Console/cake autoschema create WikiElements
  - sh app/Console/cake autoschema create WikiImages
  - sh app/Console/cake autoschema create Stammtisches

script:
  - ./app/Console/cake testsuite app Model/GeoCoordinate
  - ./app/Console/cake testsuite app Model/WikiPage
  - ./app/Console/cake testsuite app Model/WikiElement
  - ./app/Console/cake testsuite app Model/Stammtisch
  - ./app/Console/cake testsuite app Controller/AppController

#notifications:
# email: false
